PADBOL=superbol-free

.PHONY: all html rst

all: rst html

rst: _rst/$(MANUAL)/index.rst

_rst/$(MANUAL)/index.rst: ../*.texi $(MANUAL).anchors
	rm -rf _rst/$(MANUAL)/
	mkdir -p _rst/$(MANUAL)/
	$(PADBOL) texi2rst ../$(MANUAL).texi -o _rst/$(MANUAL)/

html: _html/$(MANUAL)/index.html

_html/$(MANUAL)/index.html: _rst/$(MANUAL)/index.rst  _templates/layout.html
	cp -dpR conf.py _static _templates _rst/$(MANUAL)/
	sphinx-build _rst/$(MANUAL) _html/$(MANUAL)/
